# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Contracts Quality Test

on:
  push:
    branches: [ develop ]
    paths:
      - contracts/**/*.sol
      - config/**/*.ts
      - constants/**/*.ts
      - deploy/**/*.ts
      - test/**/*.ts
  pull_request:
    branches: [ develop, master ]
    paths:
      - contracts/**/*.sol
      - config/**/*.ts
      - constants/**/*.ts
      - deploy/**/*.ts
      - test/**/*.ts
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          submodules: recursive

      - run: yarn install

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Foundry tests
        run: |
          git submodule update --init --recursive
          forge test -vvv

      - name: Compile contracts
        run: yarn compile
        
      - name: Unit tests
        run: yarn test

      - name: Unit tests (foreign)
        run: yarn test:foreign

      - name: Solidity Lint
        run: |
          yarn lint:sol

      - name: JS Lint
        run: |
          yarn lint:ts

      - name: Prettier
        run: yarn prettier
